# flyFrom,to,dateFrom,dateTo,
# ?longitudeFrom,?latitudeFrom,?radiusFrom,
# ?longitudeTo,?latitudeTo,?radiusTo,
# ?daysInDestinationFrom,?daysInDestinationTo,
# ?returnFrom,?returnTo,?typeFlight,
# ?passengers,?flyDays,?oneforcity,
# ?onlyWorkingDays,?onlyWeekends,
# ?directFlights,?locale,?partner,?partner_market,?limit,?offset

# https://api.skypicker.com/flights?v=2&sort=price&asc=1&locale=us&daysInDestinationFrom=&daysInDestinationTo=&affilid=&children=0&infants=0&flyFrom=budapest_hu&to=anywhere&featureName=aggregateResults&dateFrom=10/03/2017&dateTo=10/04/2017&typeFlight=oneway&returnFrom=&returnTo=&one_per_date=0&oneforcity=1&wait_for_refresh=0&adults=1&limit=45
# https://api.skypicker.com/flights?v=2&sort=price&asc=1&locale=us&daysInDestinationFrom=&daysInDestinationTo=&affilid=&children=0&infants=0&flyFrom=KUL&to=REP&featureName=aggregateResults&dateFrom=10/03/2017&dateTo=10/04/2017&typeFlight=oneway&returnFrom=&returnTo=&one_per_date=0&oneforcity=0&wait_for_refresh=0&adults=1&limit=45
# https://api.skypicker.com/flights?v=2&sort=price&asc=1&locale=us&daysInDestinationFrom=&daysInDestinationTo=&affilid=&children=0&infants=0&flyFrom=SIN&to=KUL&featureName=aggregateResults&dateFrom=22/10/2017&dateTo=22/10/2017&typeFlight=oneway&returnFrom=&returnTo=&one_per_date=0&oneforcity=0&wait_for_refresh=0&adults=5&limit=3
# https://api.skypicker.com/flights?v=2&sort=price&asc=1&locale=us&daysInDestinationFrom=&daysInDestinationTo=&affilid=&children=0&infants=0&flyFrom=SIN&to=KUL&featureName=results&dateFrom=23/03/2017&dateTo=23/03/2017&typeFlight=oneway&returnFrom=&returnTo=&one_per_date=0&oneforcity=0&wait_for_refresh=0&adults=5&limit=45

{u'connections': [],
 u'currency': u'EUR',
 u'currency_rate': 1,
 u'data': [{u'aTime': 1508662800,
            u'aTimeUTC': 1508634000,
            u'baglimit': {u'hand_height': 20,
                          u'hand_length': 55,
                          u'hand_weight': 7,
                          u'hand_width': 44,
                          u'hold_weight': 20},
            u'bags_price': {u'1': 25.0, u'2': 50.0},
            u'booking_token': u'GamFTRHoBQ/v6QB8IrykhpoVGKB0KA6sVANbFz24Dyu3VGSgdrTrERd1E37H1zyF2Y49gJffm0zakZDAomLI52UalpJnx+PiX1EDxTNRA0rLx/muaF0Gxd1nZU5SIZ7vlGrOMR/2GePK3q63XLIlB1ub7rg9IwBpQexYNJna3DKKtqlFUSPJymWnrG27u4zsdNViQKJVvrI3cicoFBC82AWpqY2XpehXU9k4OUH1wdEL1LpP0NnfiJ+nhfEkKXakiHq7IwVzK70b0B+hfKIcGxWkMuzdM+9rhJwucpZIQ3Rk4mj70n4XBsMEsWsubnPP/4vYAg/XnHqB8SoFBQLVfs10R0XGM23rVqVvSZhoKwZZkr5Tl8SzS0twYmEy2A7A',
            u'cityFrom': u'Singapore',
            u'cityTo': u'Kuala Lumpur',
            u'conversion': {u'EUR': 81},
            u'countryFrom': {u'code': u'SG', u'name': None},
            u'countryTo': {u'code': u'MY', u'name': u'Malaysia'},
            u'dTime': 1508659200,
            u'dTimeUTC': 1508630400,
            u'distance': 316.8,
            u'duration': {u'departure': 3600, u'return': 0, u'total': 3600},
            u'flyFrom': u'SIN',
            u'flyTo': u'KUL',
            u'fly_duration': u'1h 0m',
            u'hidden_flights': [],
            u'id': u'EK983902254_186703031',
            u'mapIdfrom': u'singapore_sg',
            u'mapIdto': u'kuala-lumpur_my',
            u'nightsInDest': None,
            u'p1': 1,
            u'p2': 1,
            u'p3': 1,
            u'price': 81,
            u'route': [{u'aTime': 1508662800,
                        u'aTimeUTC': 1508634000,
                        u'airline': u'MH',
                        u'bags_recheck_required': False,
                        u'cityFrom': u'Singapore',
                        u'cityTo': u'Kuala Lumpur',
                        u'dTime': 1508659200,
                        u'dTimeUTC': 1508630400,
                        u'flight_no': 604,
                        u'flyFrom': u'SIN',
                        u'flyTo': u'KUL',
                        u'found_on': u'travelport',
                        u'id': u'EK983902254_186703031',
                        u'latFrom': 1.28967,
                        u'latTo': 3.1412,
                        u'lngFrom': 103.85,
                        u'lngTo': 101.687,
                        u'mapIdfrom': u'singapore_sg',
                        u'mapIdto': u'kuala-lumpur_my',
                        u'original_return': 0,
                        u'price': 1,
                        u'return': 0,
                        u'source': u'GDS-r'}],
            u'transfers': []},
           {u'aTime': 1508678100,
            u'aTimeUTC': 1508649300,
            u'baglimit': {u'hand_height': 20,
                          u'hand_length': 55,
                          u'hand_weight': 7,
                          u'hand_width': 44,
                          u'hold_weight': 20},
            u'bags_price': {u'1': 25.0, u'2': 50.0},
            u'booking_token': u'GamFTRHoBQ/v6QB8IrykhpoVGKB0KA6sVANbFz24Dyu3VGSgdrTrERd1E37H1zyFeNInyf8z6GYe1L6ydl2k2VYjb4GeT2yRssK2uLz5brNliNTqo+5QeMl1tJdN9LS+gq2n9uY1rddXZH9ir0H0dECMsoJatAaklapUYmlh0TL0iv2RH3PNWCYaqWe9te8BPe6NCUJc+v2EZU1+E3mrii4KZjRrNnHeCfCZlbmxvO35yBg8mpQ3aHYWVzlnZ0FEevYjBsFlAUzevWEqTjssY9gLpNYkuDZoLYjEWv58xGjJ2iSOCfE3vCFArOILWL8gb6HqGf7COlOsvoBMQSN3YYoeWQRLNwRjP7GjH3aAMu5wi9z2B21QpJkcTKNWqIjw',
            u'cityFrom': u'Singapore',
            u'cityTo': u'Kuala Lumpur',
            u'conversion': {u'EUR': 81},
            u'countryFrom': {u'code': u'SG', u'name': None},
            u'countryTo': {u'code': u'MY', u'name': u'Malaysia'},
            u'dTime': 1508674500,
            u'dTimeUTC': 1508645700,
            u'distance': 316.8,
            u'duration': {u'departure': 3600, u'return': 0, u'total': 3600},
            u'flyFrom': u'SIN',
            u'flyTo': u'KUL',
            u'fly_duration': u'1h 0m',
            u'hidden_flights': [],
            u'id': u'EK983902261_188160310',
            u'mapIdfrom': u'singapore_sg',
            u'mapIdto': u'kuala-lumpur_my',
            u'nightsInDest': None,
            u'p1': 1,
            u'p2': 1,
            u'p3': 1,
            u'price': 81,
            u'route': [{u'aTime': 1508678100,
                        u'aTimeUTC': 1508649300,
                        u'airline': u'MH',
                        u'bags_recheck_required': False,
                        u'cityFrom': u'Singapore',
                        u'cityTo': u'Kuala Lumpur',
                        u'dTime': 1508674500,
                        u'dTimeUTC': 1508645700,
                        u'flight_no': 628,
                        u'flyFrom': u'SIN',
                        u'flyTo': u'KUL',
                        u'found_on': u'travelport',
                        u'id': u'EK983902261_188160310',
                        u'latFrom': 1.28967,
                        u'latTo': 3.1412,
                        u'lngFrom': 103.85,
                        u'lngTo': 101.687,
                        u'mapIdfrom': u'singapore_sg',
                        u'mapIdto': u'kuala-lumpur_my',
                        u'original_return': 0,
                        u'price': 1,
                        u'return': 0,
                        u'source': u'GDS-r'}],
            u'transfers': []},
           {u'aTime': 1508673900,
            u'aTimeUTC': 1508645100,
            u'baglimit': {u'hand_height': 20,
                          u'hand_length': 55,
                          u'hand_weight': 7,
                          u'hand_width': 44,
                          u'hold_weight': 20},
            u'bags_price': {u'1': 25.0, u'2': 50.0},
            u'booking_token': u'GamFTRHoBQ/v6QB8IrykhpoVGKB0KA6sVANbFz24Dyu3VGSgdrTrERd1E37H1zyFVAuZMa6PjR/Ep44wc3F//L5BtHd3IWxfRIkxVzN0F5v3ly+E3ZomrKHEaO9xiWHs1TTVc1la/agfZeMvsryL6mTPIg79EhurIEaYFIZKx7AHIsv4+Gp+goYHbj8k9TGVM4uYqxRew3zwf6WaLQArlj0J6kuamdXNzTf9ApK0Th65WcP2guQV/dpvNjZNCqnTEiitPzE0LbBFBgvz5PwBfxnJ3mIa7XsuhsVN7BKtMlb4ajjNzlHiG8v/dPEZmcx7LK/uyLs3jzZ2rwOE8mjD6MHCIia2f6Snaf/c+9qWdF8fXk/Jj7yUjlqw8DwyX7Ct',
            u'cityFrom': u'Singapore',
            u'cityTo': u'Kuala Lumpur',
            u'conversion': {u'EUR': 81},
            u'countryFrom': {u'code': u'SG', u'name': None},
            u'countryTo': {u'code': u'MY', u'name': u'Malaysia'},
            u'dTime': 1508670300,
            u'dTimeUTC': 1508641500,
            u'distance': 316.8,
            u'duration': {u'departure': 3600, u'return': 0, u'total': 3600},
            u'flyFrom': u'SIN',
            u'flyTo': u'KUL',
            u'fly_duration': u'1h 0m',
            u'hidden_flights': [],
            u'id': u'EK983902256_196233220',
            u'mapIdfrom': u'singapore_sg',
            u'mapIdto': u'kuala-lumpur_my',
            u'nightsInDest': None,
            u'p1': 1,
            u'p2': 1,
            u'p3': 1,
            u'price': 81,
            u'route': [{u'aTime': 1508673900,
                        u'aTimeUTC': 1508645100,
                        u'airline': u'MH',
                        u'bags_recheck_required': False,
                        u'cityFrom': u'Singapore',
                        u'cityTo': u'Kuala Lumpur',
                        u'dTime': 1508670300,
                        u'dTimeUTC': 1508641500,
                        u'flight_no': 614,
                        u'flyFrom': u'SIN',
                        u'flyTo': u'KUL',
                        u'found_on': u'travelport',
                        u'id': u'EK983902256_196233220',
                        u'latFrom': 1.28967,
                        u'latTo': 3.1412,
                        u'lngFrom': 103.85,
                        u'lngTo': 101.687,
                        u'mapIdfrom': u'singapore_sg',
                        u'mapIdto': u'kuala-lumpur_my',
                        u'original_return': 0,
                        u'price': 1,
                        u'return': 0,
                        u'source': u'GDS-r'}],
            u'transfers': []}],
 u'del': 0,
 u'ref_tasks': {u'EK': [{u'basic_task': True,
                         u'check_price_provider': u'AVIAC',
                         u'date': u'2017-10-22',
                         u'dst': u'KUL',
                         u'id': 1489214746641281,
                         u'pnum': 1,
                         u'refresh': True,
                         u'return_date': None,
                         u'search_request': True,
                         u'source': u'GDS',
                         u'src': u'SIN',
                         u'timestamp': 1489214746}]},
 u'refresh': [],
 u'search_params': {u'flyFrom_type': u'airport',
                    u'seats': {u'adults': 1,
                               u'children': 0,
                               u'infants': 0,
                               u'passengers': 1},
                    u'to_type': u'airport'},
 u'time': 1}
